site_name: mkdocs-dark-bug
site_description: Illustration of theme/scheme disconnect in squidfunk/mkdocs-material#2727
site_author: Matt Bogosian
repo_url: https://github.com/posita/mkdocs-dark-bug

nav:
  - Test case: index.md

extra_css:
  - image_theme.css

extra_javascript:
  # Un-comment to test reactivity to prefers-color-scheme (consider commenting out the "toggle"
  # sections under "theme" below)
  # - image_theme.js
  - image_theme_emulated.js

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences

plugins:
  - exclude:
      glob:
        - "*.py"
  - search

theme:
  name: "material"
  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
